#
# example_config.yaml
#
# Configure this file to suit your needs. 
#

# STEP 1: rename this file to "config.yaml"


paths_to_monitor : 
    "/path/to/a/website":
        # configure here what extensions you want to monitor
        # (or not to). For instance, to monitor every PHP file
        # inside /path/to/a/webiste, just add "*.php" (like 
        # the one set below)
        # you can also avoid certain files, like the example 
        # of the README.php file
        files:
            - "*.php"
            - "*.html"
            - "!README.php"
        # here you have to configure what directories you want 
        # to ignore. The directories are checked by regular 
        # expression, so regular expressions can be used to 
        # match multiple directories. 
        # For instance, "images?" would match the directories
        # "image" or "images" 
        directories_ignored:
            - "/images"

# changeMonitor uses a database to store the files and a 
# md5sum of the file; here you have to set where the 
# database is located
database: "/path/to/your/database/example.db"

# here you will have to provide the oauth info 
# information for your project. You can get your 
# own oauth info information by creating a google 
# project in the google cloud console and afterwards
# create a oauth client
installed:
    "client_id": "XXXX"
    "project_id": "XXXX"
    "auth_uri": "XXXX"
    "token_uri": "XXXXX"
    "auth_provider_x509_cert_url": "XXXX"
    "client_secret": "XXXXX"

email: 
    from: "hello@example.com"
    to: "your-email-address@example.com"
    reload: 
        subject: "RELOAD: A reload of the md5sums have been made"
        body: >
            <html>
            
            <p>Hi,</p> 
            
            <p>A complete reload of the paths have been made. If it is not you, 
            somebody is doing something really nefarious on your server. The 
            new files signatures are below. </p>
            
            #file_list
            </html>
    ok:
        subject: "OK: nothing has changed"
        body: >
            <html>
            
            <p>Hello,</p>
            
            <p>Nothing has changed in the monitored filesystems.</p>
            
            <p>Have a nice day.</p>

            </html>
    fail:
        subject: "FAIL: #numberFiles FILES HAVE BEEN ALTERED"
        body: >
            <html>
            <p>Hi,</p> 
            
            <p>It appears that some files have been altered.
            It is possible that somebody is doing something 
            nasty, check it out.</p> 
            
            #file_list

            </html>

            
            
